[package]
name = "opc_comn_bindings"
version = "0.3.0"
edition = "2024"
description = "OPC Historical Data Access bindings"
readme = "README.md"
repository = "https://github.com/Ronbb/rust_opc"
license = "MIT"
keywords = ["bindings", "comn", "opc", "opccomn"]
exclude = [".metadata/*", ".windows/*", "build.rs"]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = []

[dependencies]
windows = { workspace = true }
windows-core = { workspace = true }
windows-targets = { workspace = true }

[build-dependencies]
windows-bindgen = { workspace = true }
