[package]
name = "opc_da"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Ronbb/rust_opc"
keywords = ["opc", "da"]

[dependencies]
opc_da_bindings = { path = "../opc_da_bindings" }
globset = "0.4.15"
tokio = { version = "1.41.1", features = ["rt-multi-thread", "full"] }
windows = { version = "0.58.0", features = [
    "implement",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Variant",
    "Win32_System_WinRT",
] }
windows-core = "0.58.0"

[override]
