[package]
name = "opc_classic_utils"
version = "0.3.0"
edition = "2024"
description = "OPC Classic utilities and common functionality"
readme = "README.md"
repository = "https://github.com/Ronbb/rust_opc"
license = "MIT"
keywords = ["classic", "opc", "utilities", "utils"]

[dependencies]
windows = { workspace = true }
windows-core = { workspace = true }